In [8]:
import numpy as np
k = array([[ 0, 4, 2], [ 9, 3, 7]])

NameError: name 'array' is not defined

In [9]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4]) 

In [10]:
c = a - b 
c

array([10, 10, 10, 10])

In [11]:
a = 9/2 
b = 5.2/2

In [13]:
a

4.5

In [14]:
b

2.6

In [18]:
import pandas as pd


In [19]:
series = pd.series(3,index=['a','b','c'])

AttributeError: module 'pandas' has no attribute 'series'

In [20]:
a=np.array(5,8,12,65)

ValueError: only 2 non-keyword arguments accepted

In [21]:
a=np.array([5,8,12,65])

In [22]:
a

array([ 5,  8, 12, 65])

In [23]:
m= np.zeros((3,3))

In [24]:
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])